env: test

base_url:
  test: https://api.escuelajs.co/api/v1
  dev: https://dev-api.xxx.com
  prod: https://prod-api.xxx.com

login:
  email: john@mail.com
  password: changeme

mysql:
 host: 127.0.0.1
 port: 3306
 user: root
 password: "123456"
 database: test